/*
 * This source file was generated by the Gradle 'init' task
 */
package self.humbleseer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CaffeinettyTest {
    @Test
    void Hello() {
        System.out.println("Hello");
    }
}
